name: Docker Build & Publish

on:
  push:
    branches: [main, master]

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code 🛎️
        uses: actions/checkout@v4

      - name: Set up Docker Buildx 🚀
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub 🚢
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and push 🏗️
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME}}/${{ secrets.docker_repository }}:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME}}/${{ secrets.docker_repository }}:latest
          secrets: |
            "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}"
            "POSTGRES_URL=${{ secrets.POSTGRES_URL }}"
            "POSTGRES_USER=${{ secrets.POSTGRES_USER }}"
            "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}"
            "POSTGRES_DB=${{ secrets.POSTGRES_DB }}"
            "GITHUB_APP_CLIENT_ID=${{ secrets.GH_APP_CLIENT_ID }}"
            "GITHUB_APP_CLIENT_SECRET=${{ secrets.GH_APP_CLIENT_SECRET }}"
            "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}"
            "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}"
            "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}"
            "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}"
            "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}"
            "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}"
            "AWS_BUCKET_REGION=${{ secrets.AWS_BUCKET_REGION }}"
            "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
            "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            "PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}"
            "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
